### PR TITLE
adding java support

### PR DESCRIPTION
**Pull request by jegonzal**
This will allow us to run Spark using the following sequence of commands from within a jupyter notebook.  (I have tested it locally in this Docker image):

```python
# Download and extract tar
!curl -O https://d3kbcqa49mib13.cloudfront.net/spark-2.2.0-bin-hadoop2.7.tgz
!tar -xvf spark-2.2.0-bin-hadoop2.7.tgz

# Installing spark finding tools
!pip install findspark

# Initialize Spark
import os
import findspark
os.environ["PYSPARK_PYTHON"] = "python3"
findspark.init("spark-2.2.0-bin-hadoop2.7",)

# Launch Spark Session
from pyspark.sql import SparkSession, Column, Row, functions as F 
spark = (
    SparkSession.builder
        .master("local[*]")
        .appName("LectureExample")
        .getOrCreate()
)
sc = spark.sparkContext

# Test Spark 
numbers = sc.parallelize(range(32))
numbers.sum()
```

### CODE REVIEW

**Comment by fperez** [comment]
Ack, thx! @ryanlovett do you have any thoughts on having Java on the images? Unless you see a problem with this, we'll go ahead and merge/propagate if Travis is happy.

**Comment by jegonzal** [comment]
I checked with @ryanlovett and he didn't have concerns about java but
cautioned against loading all the cores with Spark.  However, since we
don't have exercises planned I don't think this will be an issue.

**Comment by fperez** [comment]
Great! then let's go ahead as Travis permits.

**Comment by fperez** [comment]
merged, now we need to wait for the deployment checks on staging, then repeat on prod.

**Comment by ryanlovett** [comment]
Reposting from slack about the state of staging:

> yuvipanda and i have to resolve an issue with the staging hub this afternoon on ssl/letsencrypt support. that would delay when you could merge your changes. i'll keep you posted though; hopefully we'll resolve this afternoon.

and later:
> We weren't able to resolve the core ssl issue which appears to be related to azure's networking. The problem affects let's encrypt cert provisioning so I'm going to work around it by getting certs from campus. At the moment, the staging hub will work okay without ssl, but you have to disable hsts in your browser manually. This should be fixed sometime tomorrow after we're issued the certs.

Sorry for the delay!

**Comment by fperez** [comment]
No worries, thanks for the update @ryanlovett !

**Pull request merged**
