### PR TITLE
Update JupyterLab to 0.31.2

### PR DESCRIPTION
**Pull request by ryanlovett**

### CODE REVIEW

**Comment by fperez** [comment]
Mmh, @ryanlovett, I'm confused why merging #44 is itself a new PR?

**Comment by ryanlovett** [comment]
There's one PR from your fork's staging branch to this repo's staging branch, then there's a merge. The merge causes the staging hub to get all of the updates.

After that there's a PR from this repo's staging branch to this repo's prod branch, then there's a merge. That merge causes the prod hub to get all of the updates.

So this thread has reached the latter PR and the change is ready to be merged to prod. Sometimes I will get everything right up to where it is ready to be merged to prod, but I'll hold off because there are a lot of people active. I don't think that's the case here since that was at 10p last night. I'll go ahead with the merge now.

**Comment by ryanlovett** [comment]
This CI is being held up by jupyterhub/zero-to-jupyterhub-k8s#466. I need to downgrade helm and try again.

**Comment by fperez** [comment]
Ah, I missed that this is a cross-branch PR! Thanks for the patient explanation, sorry for bugging you :)

No worries on the hold, this is pure candy and not urgent at all.

**Comment by ryanlovett** [comment]
No trouble at all!

**Pull request merged**
